services:
  app:
    container_name: starql
    image: starql:latest
    volumes:
      - ./logs:/logs
      - ./data:/data
      - ./results:/results
    env_file:
      - app.env
    network_mode: host
