services:
  app:
    container_name: starql
    image: starql:latest
    volumes:
      - ./logs:/logs
      - ./data:/data
      - ./results:/results
      - ./shuffled_train.jsonl:/app/shuffled_mini_dev_postgresql.jsonl
    env_file:
      - app.env
    network_mode: host
    tty: true
